In [13]:
import pandas as pd
pd.options.display.float_format = '{:.5f}'.format
import numpy as np
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)
import warnings
warnings.filterwarnings("ignore")

In [14]:
import os.path
def path_base(base_name):
    current_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
    print(current_dir)
    data_dir = current_dir.replace('notebook','data')
    print(data_dir)
    data_base = data_dir + '\\' + base_name
    print(data_base)
    return data_base

In [15]:
base = pd.read_csv(path_base('db_risco_credito_sm.csv'))

C:\MyPhyton\DataScience\notebook
C:\MyPhyton\DataScience\data
C:\MyPhyton\DataScience\data\db_risco_credito_sm.csv


In [16]:
base.head(3)

historia divida garantias     renda risco
0          ruim   alta   nenhuma      0_15  alto
1  desconhecida   alta   nenhuma     15_35  alto
2  desconhecida  baixa   nenhuma  acima_35  alto

In [5]:
base.describe()

historia divida garantias     renda risco
count             11     11        11        11    11
unique             4      2         2         3     2
top     desconhecida   alta   nenhuma  acima_35  alto
freq               4      6         9         6     6

In [6]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
historia     11 non-null object
divida       11 non-null object
garantias    11 non-null object
renda        11 non-null object
risco        11 non-null object
dtypes: object(5)
memory usage: 568.0+ bytes


In [7]:
previsores = base.iloc[:,0:4].values
classe = base.iloc[:,4].values

In [8]:
print(previsores)
print(classe)

[['ruim' 'alta' 'nenhuma' '0_15']
 ['desconhecida' 'alta' 'nenhuma' '15_35']
 ['desconhecida' 'baixa' 'nenhuma' 'acima_35']
 ['desconhecida' 'baixa' 'nenhuma' 'acima_35']
 ['desconhecida' 'baixa' 'adequada' 'acima_35']
 ['ruim' 'baixa' 'nenhuma' '0_15']
 ['boa' 'baixa' 'nenhuma' 'acima_35']
 ['boa' 'alta' 'adequada' 'acima_35']
 ['boa' 'alta' 'nenhuma' '0_15']
 ['boa ' 'alta' 'nenhuma' 'acima_35']
 ['ruim' 'alta' 'nenhuma' '15_35']]
['alto' 'alto' 'alto' 'baixo' 'baixo' 'alto' 'baixo' 'baixo' 'alto'
 'baixo' 'alto']


In [22]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [23]:
previsores[:,0] = labelencoder.fit_transform(previsores[:,0])
previsores[:,1] = labelencoder.fit_transform(previsores[:,1])
previsores[:,2] = labelencoder.fit_transform(previsores[:,2])
previsores[:,3] = labelencoder.fit_transform(previsores[:,3])

In [24]:
print(previsores)

[[3 0 1 0]
 [2 0 1 1]
 [2 1 1 2]
 [2 1 1 2]
 [2 1 0 2]
 [3 1 1 0]
 [0 1 1 2]
 [0 0 0 2]
 [0 0 1 0]
 [1 0 1 2]
 [3 0 1 1]]


In [25]:
from sklearn.linear_model import LogisticRegression
classificador = LogisticRegression()
classificador.fit(previsores, classe)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
print(classificador.intercept_)
print(classificador.coef_)

[-0.52358972]
[[-0.65034407  0.25428474 -0.45375558  1.17384764]]


In [27]:
# história boa, dívida alta, garantias nenhuma, renda > 35
# história ruim, dívida alta, garantias adequada, renda < 15
resultado = classificador.predict([[0,0,1,2], [3, 0, 0, 0]])
resultado2 = classificador.predict_proba([[0,0,1,2], [3, 0, 0, 0]])
print(resultado)
print(resultado2)

['baixo' 'alto']
[[0.20256331 0.79743669]
 [0.92234346 0.07765654]]
