In [10]:
import pandas as pd
pd.options.display.float_format = '{:.5f}'.format
import numpy as np
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)
import warnings
warnings.filterwarnings("ignore")

In [11]:
import os.path
def path_base(base_name):
    current_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
    print(current_dir)
    data_dir = current_dir.replace('notebook','data')
    print(data_dir)
    data_base = data_dir + '\\' + base_name
    print(data_base)
    return data_base

In [12]:
base = pd.read_csv(path_base('db_preco_casas.csv'))

C:\MyPhyton\DataScience\notebook
C:\MyPhyton\DataScience\data
C:\MyPhyton\DataScience\data\db_preco_casas.csv


In [13]:
base.head(3)

id             date        price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000 221900.00000         3    1.00000         1180   
1  6414100192  20141209T000000 538000.00000         3    2.25000         2570   
2  5631500400  20150225T000000 180000.00000         2    1.00000          770   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650 1.00000           0     0  ...      7        1180              0   
1      7242 2.00000           0     0  ...      7        2170            400   
2     10000 1.00000           0     0  ...      6         770              0   

   yr_built  yr_renovated  zipcode      lat       long  sqft_living15  \
0      1955             0    98178 47.51120 -122.25700           1340   
1      1951          1991    98125 47.72100 -122.31900           1690   
2      1933             0    98028 47.73790 -122.23300           2720   

   sqft_lot15  
0        5650  
1        7639  
2        8062  

[3 rows x 21 columns]

In [5]:
base.shape

(21613, 21)

In [38]:
X = base.iloc[:,3:19].values
print(X[0:1])

[[ 3.00000e+00  1.00000e+00  1.18000e+03  5.65000e+03  1.00000e+00
   0.00000e+00  0.00000e+00  3.00000e+00  7.00000e+00  1.18000e+03
   0.00000e+00  1.95500e+03  0.00000e+00  9.81780e+04  4.75112e+01
  -1.22257e+02]]


In [39]:
y = base.iloc[:,2:3].values
print(y)

[[221900.]
 [538000.]
 [180000.]
 ...
 [402101.]
 [400000.]
 [325000.]]


In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)

In [42]:
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

In [43]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X,
                                                                 y,
                                                                 test_size = 0.3,
                                                                 random_state=0)

In [44]:
print(X_treinamento.shape)
print(X_teste.shape)
print(y_treinamento.shape)
print(y_teste.shape)

(15129, 16)
(6484, 16)
(15129, 1)
(6484, 1)


In [45]:
from sklearn.neural_network import MLPRegressor
regressor = MLPRegressor(hidden_layer_sizes=(9,9))

In [46]:
regressor.fit(X_treinamento,y_treinamento)

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(9, 9), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=200,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

# Score

In [47]:
score = regressor.score(X_treinamento,y_treinamento)
score

0.8944223889591512

In [48]:
score_teste = regressor.score(X_teste,y_teste)
score_teste

0.8828595794360343

# PREVISÕES

In [49]:
previsoes = regressor.predict(X_teste)
print(previsoes)

[-0.6301704   3.18091436 -0.04495241 ... -0.45362037 -0.87994919
 -0.89998652]


In [53]:
y_teste = scaler_y.inverse_transform(y_teste)
previsoes = scaler_y.inverse_transform(previsoes)

In [54]:
y_teste

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [55]:
previsoes

array([ 308740.80259582, 1707861.29599024,  523585.27073918, ...,
        373555.62154709,  217042.3346901 ,  209686.25747855])

In [56]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [57]:
mae = mean_absolute_error(y_teste,previsoes)
mae

75756.32966576327

In [58]:
mse = mean_squared_error(y_teste,previsoes)
mse

16082436954.775328