In [5]:
import pandas as pd
import pickle
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [6]:
import os.path
def path_base(base_name):
    current_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
    print(current_dir)
    data_dir = current_dir.replace('notebook','data')
    print(data_dir)
    data_base = data_dir + '\\' + base_name
    print(data_base)
    return data_base

In [7]:
base = pd.read_csv(path_base('db_dados_credito.csv'))

C:\MyPhyton\DataScience\notebook
C:\MyPhyton\DataScience\data
C:\MyPhyton\DataScience\data\db_dados_credito.csv


In [8]:
base.loc[base.age < 0, 'age'] = 40.92  

previsores = base.iloc[:, 1:4]
classe = base.iloc[:, 4]

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(previsores.iloc[:, 0:3])

previsores.iloc[:, 0:3] = imputer.transform(previsores.iloc[:,0:3])
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

In [5]:
svm = pickle.load(open('svm_finalizado.sav', 'rb'))
random_forest = pickle.load(open('random_forest_finalizado.sav', 'rb'))
mlp = pickle.load(open('mlp_finalizado.sav', 'rb'))

In [6]:
resultado_svm = svm.score(previsores, classe)
resultado_random_forest = random_forest.score(previsores, classe)
resultado_mlp = mlp.score(previsores, classe)

In [7]:
print(resultado_svm)
print(resultado_random_forest)
print(resultado_mlp)

0.989
1.0
1.0


In [6]:
novo_registro = [[50000, 40, 5000]]
novo_registro = np.asarray(novo_registro)
novo_registro = novo_registro.reshape(-1, 1)
novo_registro = scaler.fit_transform(novo_registro)
novo_registro = novo_registro.reshape(-1, 3)

In [7]:
resposta_svm = svm.predict(novo_registro)
resposta_random_forest = random_forest.predict(novo_registro)
resposta_mlp = mlp.predict(novo_registro)

In [8]:
resposta_svm

array([0], dtype=int64)

In [9]:
resposta_random_forest

array([0], dtype=int64)

In [10]:
resposta_mlp

array([0], dtype=int64)

In [13]:
paga = 0 
nao_paga = 0

In [14]:
if resposta_svm[0] == 1:
    paga += 1
else:
    nao_paga += 1

In [15]:
if resposta_random_forest[0] == 1:
    paga += 1
else:
    nao_paga += 1

In [16]:
if resposta_mlp[0] == 1:
    paga += 1
else:
    nao_paga += 1

In [17]:
if paga > nao_paga:
    print('Cliente paga')
elif paga > nao_paga:
    print('Resultado empatado')
else: 
    print('Cliente não paga')

Cliente não paga
